name: hidden
favicon: null
layout_spectrum: 0.10617962409742177
typography_spectrum: 0.4608979660551995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.906989669194445
  lightness: 0.019852281315252185
  saturation: 0.1754007232375443
  rhythmicContrast: 0.46351067908108234
purpose: []
